import type { Request, Response } from "express";
import Handlebars from "handlebars";

const reportTemplate = Handlebars.compile(`# {{title}}

{{#each sections}}
## {{this.heading}}

{{this.content}}

{{/each}}
---
*Generated by AgentBazaar Format Agent*
`);

export function formatHandler(req: Request, res: Response): void {
  const { title, sections } = req.body;

  if (!title || typeof title !== "string") {
    res.status(400).json({ error: "Missing required field: title" });
    return;
  }

  if (!Array.isArray(sections) || sections.length === 0) {
    res.status(400).json({ error: "Missing required field: sections (non-empty array)" });
    return;
  }

  for (const section of sections) {
    if (!section.heading || !section.content) {
      res.status(400).json({
        error: "Each section must have heading and content fields",
      });
      return;
    }
  }

  const markdown = reportTemplate({ title, sections });

  res.json({ markdown });
}
